apiVersion: v1
kind: Service
metadata:
  name: scratch
spec:
  selector:
    app: scratch
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scratch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scratch
  template:
    metadata:
      labels:
        app: scratch
    spec:
      containers:
        - name: scratch
          image: 622138437460.dkr.ecr.us-west-2.amazonaws.com/scratch3:v1
          ports:
            - containerPort: 80
